### ISSUE TITLE
text hard to read with dark theme

### ISSUE THREAD

**Issue by severoraz** [RobertKrajewski/Sync-my-L2P#114] opened 2017-11-15 19:25 UTC
I am using a dark theme and I find some bits of text in the app hard to read, because they appear to be hardcoded-ly black, while other text does take on an automatic color. 

Examples of text that shows black when using a dark theme:
- element names in the Filebrowser tree view
- entries in the Log view

Maybe there is some stylesheet somewhere or something equivalent which is forcing this texts to be black.

**Comment by Sync-my-L2P** [comment] 2017-12-09 16:22
Thanks for letting me know. The issue is this line: https://github.com/Sync-my-L2P/Sync-my-L2P/blob/0a3f64f74bd398cbc17f25b69f81dd1504c98f80/structureelement.cpp#L116

Depending on the synchronization state, a color is chosen for each element in the tree view. Currently all colors are hard-coded, but as I just found out, you can access the default color palette via http://doc.qt.io/qt-5/qapplication.html#palette-1 . I will try to integrate this into v2.3.0.

**Comment by severoraz** [comment] 2017-12-09 23:36
Great, thanks for looking into it!

**Comment by RobertKrajewski** [comment] 2019-02-24 16:56
fixed in f33c2aca2175757674d3a35c1253ba9099b72da6

**Closed by RobertKrajewski** 2019-02-24 16:56 UTC
Labels: Feature Request, in progress
