### ISSUE TITLE
Linux AppImage not working under Fedora 30 [Qt / SSL incompatible]

### ISSUE THREAD

**Issue by mabachel** [RobertKrajewski/Sync-my-L2P#153] opened 2019-10-08 07:19 UTC
**Describe the bug**
If I double click SyncMyL2P-2.4.1-linux.AppImage a window opens but closes instantly. SyncMyL2P does not start suuccessfully

**To Reproduce**
1. Open Terminal 
2. Run ./SyncMyL2P-2.4.1-linux.AppImage 
3. See error:

```
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)
```

**Expected behavior**
Start and show up on screen

**Desktop (please complete the following information):**
 - OS: Fedora 30 (Linux)
 - Version: 5.2.17-200.fc30.x86_64

**Additional context**
qt5: 5.12.4-4.fc30
OpenSSL 1.1.1d FIPS  10 Sep 2019
GNOME 3.32.2
SyncMyL2P-2.4.1-linux
libwayland-server: 1.17.0-1.fc30                                       
qt5-qtwayland: 5.12.4-7.fc30                              
xorg-x11-server-Xwayland: 1.20.5-7.fc30

**Comment by RobertKrajewski** [comment] 2020-10-18 13:56
Confirmed duplicate of #140

**Closed by RobertKrajewski** 2020-10-18 13:56 UTC
