### ISSUE TITLE
RWTHmoodle directory's name not trimmed from spaces (error in Combination with OneDrive)

### ISSUE THREAD

**Issue by PJungkamp** [RobertKrajewski/Sync-my-L2P#154] opened 2019-10-10 17:00 UTC
I'm syncing the Moodle files to a Onedrive directory. 
On the Event "Grundgebiete der Informatik 3 - Optimierung, Modellierung und Parallelität (VO) [61.01667]" the name gets cut of after "Parallelität ". 
The space after "Parallität " causes OneDrive to fail syncronization, throwing an exception like this:
![image](https://user-images.githubusercontent.com/56401138/66589647-43b07800-eb8f-11e9-9f5b-6a98aa95f308.png)

I don't know which instance shortens the Name of the Event, but it would already help if the string declaring the directory's name would be trimmed from empty spaces before a folder is created/used.

**Comment by PJungkamp** [comment] 2019-10-10 18:08
Als fix scheint eine Änderung in "Utils.cpp" Zeile 47 zu genügen. Habe "element_text" gegen "element_text.trimmed()" ausgetauscht. Das Problem scheint behoben.

**Comment by mwkroening** [comment] 2019-10-10 18:19
This is probably a duplicate of #142.

**Comment by RobertKrajewski** [comment] 2020-10-18 08:57
Can confirm, that this is a duplicate of #142.

**Closed by RobertKrajewski** 2020-10-18 08:57 UTC
