### ISSUE TITLE
Create Folder

### ISSUE THREAD

**Issue by J0R0W** [RobertKrajewski/Sync-my-L2P#144] opened 2019-05-16 10:23 UTC
L2P Stops downloading, if a course contains symbols, which are not allowed in Windows Folder Names. The following Symbols are not allowed: ? * < > . , \ + : = / " ; [ ] |

L2P Sync should replace these symbols to symbols, which are valid.

![error](https://user-images.githubusercontent.com/18270112/57846791-4623c700-77d5-11e9-99ae-3c70fe1638f2.PNG)

**Comment by RobertKrajewski** [comment] 2019-05-17 18:37
Duplicate of #135 , closing as nor version specified neither log given

**Closed by RobertKrajewski** 2019-05-17 18:37 UTC
