### ISSUE TITLE
Moodle not reachable when using Ubuntu 19.04

### ISSUE THREAD

**Issue by jsuilmann** [RobertKrajewski/Sync-my-L2P#140] opened 2019-04-26 19:36 UTC
**Describe the bug**
Moodle can not be reached when using a fresh install of Ubuntu 19.04

**To Reproduce**
1. Run latest Appimage on Ubuntu 19.04
2. Click on 'Log in'

**Expected behavior**
Moodle should be reachable as it is using Ubuntu 18.10

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 19.04

**Additional context**
```
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
```

**Comment by RobertKrajewski** [comment] 2019-04-27 18:16
This problem is caused by AppImage and no solution has been provided yet: https://github.com/probonopd/linuxdeployqt/issues/209

**Comment by RobertKrajewski** [comment] 2019-05-03 15:31
Manually installing OpenSSL 1.0 may resolve the issue

**Comment by Mebus** [comment] 2019-05-03 16:11
Would it be possible to bundle the proper OpenSSL in the AppImage?

**Comment by RobertKrajewski** [comment] 2019-05-03 16:34
As stated in the linuxdeplyqt issue, currently no

**Comment by jsuilmann** [comment] 2019-05-04 09:41
> Manually installing OpenSSL 1.0 may resolve the issue

Thank you for the info, works for me. Installation instructions can be found on [OpenSSL's Github](https://github.com/openssl/openssl/blob/master/INSTALL)

**Comment by rayl3r** [comment] 2019-05-20 20:16
@jsuilmann Which version of OpenSSL did you install ? I tried the latest one and it does not work for me.

**Comment by RobertKrajewski** [comment] 2019-05-21 06:21
> @jsuilmann Which version of OpenSSL did you install ? I tried the latest one and it does not work for me.

You need OpenSSL 1.0.x but NOT 1.1.x

**Comment by rayl3r** [comment] 2019-05-21 08:15
@RobertKrajewski That´s what i tried, but i already have 1.1 installed and it does not change if i install a 1.0 version. Maybe i have to install openssl first, but i have some concerns to do that.

**Comment by claell** [comment] 2019-06-23 14:03
I am experiencing the same issue. So a few thoughts:

- The linuxdeployqt issue states that it only happens for pre Qt 5.10 applications, so would it be possible to switch to a newer version of Qt with Sync-My-L2P?

> As stated in the linuxdeplyqt issue, currently no

I read some discussion whether that would be a good practise (size and security getting worse), but never read that it is not possible. Or would linuxdeployqt first have to integrate it, so you can make use of it?

**Comment by claell** [comment] 2019-09-09 14:44
@RobertKrajewski Take a look at https://github.com/qTox/qTox/pull/5747 it seems they bundled their own version of openSSL as @Mebus suggested. I hope, you have the time to do that. Else we have to hope that linuxdeployqt bundles a private copy out of the box as suggested in their issue.

**Comment by claell** [comment] 2019-09-20 10:57
@RobertKrajewski Just another heads up. The official solution from `linuxdeployqt` is to use Qt 5.10 or later. Would that work for this application?

**Comment by D-VR** [comment] 2019-11-05 14:02
@claell 

 Sync-my-L2P/linux/Dockerfile 
`
RUN apt-get update && apt-get install -y qt5-default qt5-qmake libssl-dev git build-essential qttools5-dev-tools`

Could try creating the App-Image with higher Qt versions and see if anything breaks

**Comment by claell** [comment] 2019-11-05 18:35
I fear that I don't know how to build the AppImage. Also there is some authentication key needed to build it. Or can it be built directly from the Dockerfile? I have problems understanding your post.

**Comment by RobertKrajewski** [comment] 2020-10-18 16:01
V2.4.2 (#ec28291) was compiled using QT 5.11 for Linux. Problem should be fixed

**Closed by RobertKrajewski** 2020-10-18 16:01 UTC
Labels: Bug

**Comment by jadafi** [comment] 2020-10-27 12:40
Unfortunately it is not fixed. The error is still present with v2.4.2

**Comment by stormrider3106** [comment] 2020-10-27 15:34
> Unfortunately it is not fixed. The error is still present with v2.4.2

Are you still using Ubuntu 19.04?
